# This file is used to configure GitHub Pages

# Use the main branch for GitHub Pages
source:
  branch: main
  path: /

# Enforce HTTPS
enforce_https: true

# Use a custom domain (optional)
# custom_domain: www.yourdomain.com

# Disable Jekyll processing
markdown: false
